<?php
declare(strict_types=1);
namespace StageArtTicket\Domain\Ticket;
final class TicketRepository{
 private \wpdb $db;private string $r;private string $c;private string $l;private string $pf;
 public function __construct(?\wpdb $db=null){global $wpdb;$this->db=$db??$wpdb;$p=$this->db->prefix;$this->r=$p.'stageart_plugin_ticket_reservations';$this->c=$p.'stageart_plugin_ticket_checkins';$this->l=$p.'stageart_plugin_ticket_sales_links';$this->pf=$p.'stageart_plugin_production_performances';}
 public function capacity(int $id):int{return(int)$this->db->get_var($this->db->prepare("SELECT capacity FROM {$this->pf} WHERE id=%d",$id));}
 public function setCapacity(int $id,int $capacity):bool{return false!==$this->db->update($this->pf,['capacity'=>max(0,$capacity)],['id'=>$id],['%d'],['%d']);}
 public function reservations(int $id):array{return $this->db->get_results($this->db->prepare("SELECT r.*,c.id AS checkin_id,c.checked_in_at FROM {$this->r} r LEFT JOIN {$this->c} c ON c.reservation_id=r.id WHERE r.performance_id=%d AND r.status='confirmed' ORDER BY r.created_at,r.id",$id),ARRAY_A)?:[];}
 public function reservedQuantity(int $id):int{return(int)$this->db->get_var($this->db->prepare("SELECT COALESCE(SUM(quantity),0) FROM {$this->r} WHERE performance_id=%d AND status='confirmed'",$id));}
 public function checkInCount(int $id):int{return(int)$this->db->get_var($this->db->prepare("SELECT COALESCE(SUM(r.quantity),0) FROM {$this->r} r INNER JOIN {$this->c} c ON c.reservation_id=r.id WHERE r.performance_id=%d AND r.status='confirmed'",$id));}
 public function findSalesLink(int $pid,string $slug):?array{$x=$this->db->get_row($this->db->prepare("SELECT * FROM {$this->l} WHERE production_id=%d AND slug=%s AND status='publish' LIMIT 1",$pid,$slug),ARRAY_A);return$x?:null;}
 public function salesLinks(int $pid):array{return $this->db->get_results($this->db->prepare("SELECT * FROM {$this->l} WHERE production_id=%d ORDER BY id",$pid),ARRAY_A)?:[];}
 public function saveSalesLink(int $pid,int $uid,string $slug):int{$slug=sanitize_title($slug);$now=gmdate('Y-m-d H:i:s');$old=$this->db->get_row($this->db->prepare("SELECT id FROM {$this->l} WHERE production_id=%d AND authcore_user_id=%d LIMIT 1",$pid,$uid),ARRAY_A);if($old){$this->db->update($this->l,['slug'=>$slug,'status'=>'publish','updated_at'=>$now],['id'=>(int)$old['id']],['%s','%s','%s'],['%d']);return(int)$old['id'];}$this->db->insert($this->l,['production_id'=>$pid,'authcore_user_id'=>$uid,'slug'=>$slug,'status'=>'publish','created_at'=>$now,'updated_at'=>$now],['%d','%d','%s','%s','%s','%s']);return(int)$this->db->insert_id;}
 public function createReservation(array $d):int{$now=gmdate('Y-m-d H:i:s');$this->db->insert($this->r,['reservation_no'=>$d['reservation_no'],'production_id'=>(int)$d['production_id'],'performance_id'=>(int)$d['performance_id'],'customer_name'=>$d['customer_name'],'customer_name_kana'=>$d['customer_name_kana'],'customer_email'=>$d['customer_email'],'quantity'=>(int)$d['quantity'],'authcore_user_id'=>(int)$d['authcore_user_id'],'source'=>$d['source']??'online','status'=>'confirmed','created_at'=>$now,'updated_at'=>$now],['%s','%d','%d','%s','%s','%s','%d','%d','%s','%s','%s','%s']);return(int)$this->db->insert_id;}
 public function reserveIfAvailable(array $d,int $capacity):int{$qty=(int)$d['quantity'];$this->db->query('START TRANSACTION');try{$used=(int)$this->db->get_var($this->db->prepare("SELECT COALESCE(SUM(quantity),0) FROM {$this->r} WHERE performance_id=%d FOR UPDATE",(int)$d['performance_id']));if($used+$qty>$capacity){$this->db->query('ROLLBACK');return 0;}$id=$this->createReservation($d);if(!$id)throw new \RuntimeException('insert failed');$this->db->query('COMMIT');return$id;}catch(\Throwable $e){$this->db->query('ROLLBACK');return 0;}}
 public function doorReservation(int $productionId,int $performanceId,int $uid,int $qty):int{$id=$this->createReservation(['production_id'=>$productionId,'performance_id'=>$performanceId,'customer_name'=>'当日券','customer_name_kana'=>'トウジツケン','customer_email'=>'','quantity'=>$qty,'authcore_user_id'=>$uid,'source'=>'door','reservation_no'=>$this->nextReservationNo('DAY')]);if($id)$this->checkIn($id,get_current_user_id());return$id;}
 public function checkIn(int $id,?int $by=null):bool{$x=$this->db->get_var($this->db->prepare("SELECT id FROM {$this->c} WHERE reservation_id=%d",$id));if($x)return false;$now=gmdate('Y-m-d H:i:s');return false!==$this->db->insert($this->c,['reservation_id'=>$id,'checked_in_at'=>$now,'checked_in_by'=>$by,'created_at'=>$now],['%d','%s','%d','%s']);}
 public function nextReservationNo(string $prefix):string{$date=wp_date('Ymd',current_time('timestamp',true));$n=(int)$this->db->get_var($this->db->prepare("SELECT COUNT(*) FROM {$this->r} WHERE reservation_no LIKE %s",$prefix.'-'.$date.'-%'));return sprintf('%s-%s-%04d',$prefix,$date,$n+1);}
}
