<?php
declare(strict_types=1);
namespace StageArtTicket\Presentation\PublicSite;
use StageArtCore\Domain\Production\ProductionRepository;
use StageArtTicket\Domain\Ticket\TicketRepository;
final class TicketRouter{
 private TicketRepository $t;private ProductionRepository $p;
 public function __construct(){$this->t=new TicketRepository();$this->p=new ProductionRepository();}
 public function register():void{add_action('init',[$this,'rewrite']);add_filter('query_vars',[$this,'vars']);add_action('template_redirect',[$this,'render'],1);}
 public function rewrite():void{add_rewrite_rule('^production/([^/]+)/ticket/?$','index.php?stageart_ticket_production_slug=$matches[1]','top');add_rewrite_rule('^production/([^/]+)/ticket/([^/]+)/?$','index.php?stageart_ticket_production_slug=$matches[1]&stageart_ticket_attribution_slug=$matches[2]','top');}
 public function vars(array$v):array{$v[]='stageart_ticket_production_slug';$v[]='stageart_ticket_attribution_slug';return$v;}
 private function prod(string$s):?\WP_Post{$q=new \WP_Query(['post_type'=>'stageart_production','name'=>$s,'post_status'=>'publish','posts_per_page'=>1]);return$q->posts[0]??null;}
 private function start(int$id):string{$m=get_post_meta($id);return(string)($m['ticket_sales_start_at'][0]??'');}
 private function state(array$x,string$start):string{$n=new \DateTimeImmutable('now',new \DateTimeZone('UTC'));if($start!=='')try{if($n<new \DateTimeImmutable($start,new \DateTimeZone('UTC')))return'before';}catch(\Throwable){return'before';}try{$e=new \DateTimeImmutable($x['performance_date'].' 00:00:00',new \DateTimeZone('Asia/Tokyo'));if($n>=$e->setTimezone(new \DateTimeZone('UTC')))return'ended';}catch(\Throwable){}return((int)$x['capacity']-$this->t->reservedQuantity((int)$x['id']))<=0?'full':'open';}
 private function attrs(int$id):array{$a=[];foreach($this->p->participants($id)as$x)if(!empty($x['auth_user_id'])){$uid=(int)$x['auth_user_id'];$a[$uid]=['id'=>$uid,'name'=>(string)$x['name']];}return$a;}
 private function prices(int$id):void{$m=get_post_meta($id);$tax=(string)($m['tax_display'][0]??'included');$r=array_filter($this->p->tickets($id),static fn($x)=>!empty($x['show_on_reservation']));if(!$r)return;echo'<section><h2>チケット</h2><ul>';foreach($r as$x)echo'<li>'.esc_html($x['description']).'：'.number_format((int)$x['amount']).'円'.($tax==='included'?'（税込）':($tax==='excluded'?'（税別）':'')).'</li>';echo'</ul></section>';}
 private function field(string$l,string$n,string$ty,string$extra=''):void{echo'<p><label>'.esc_html($l).'<br><input required name="'.esc_attr($n).'" type="'.esc_attr($ty).'" '.$extra.'></label></p>';}
 public function render():void{$slug=(string)get_query_var('stageart_ticket_production_slug');if($slug==='')return;$pr=$this->prod($slug);if(!$pr)return;$fixed=(string)get_query_var('stageart_ticket_attribution_slug');$link=$fixed!==''?$this->t->findSalesLink((int)$pr->ID,$fixed):null;if($fixed!==''&&!$link){status_header(404);return;}$ps=$this->p->performances((int)$pr->ID);$attrs=$this->attrs((int)$pr->ID);$key=sanitize_text_field((string)($_GET['stageart_ticket_confirm']??''));if($key!==''){$d=get_transient($key);if(!$d)wp_die('予約確認の有効期限が切れています。');$this->confirm($pr,$d,$key);return;}if(isset($_POST['stageart_ticket_submit'])){$this->prepare($pr,$ps,$attrs,$link);return;}get_header();echo'<main class="stageart-ticket"><article><h1>'.esc_html($pr->post_title).'</h1>';$this->prices((int)$pr->ID);$s=$this->start((int)$pr->ID);echo'<form method="post">';wp_nonce_field('stageart_ticket_reserve','stageart_ticket_nonce');echo'<p><label>公演回<br><select required name="performance_id"><option value="">選択してください</option>';foreach($ps as$x){$st=$this->state($x,$s);$label=$x['performance_date'].' '.substr((string)$x['start_time'],0,5);echo'<option value="'.(int)$x['id'].'" '.($st!=='open'?'disabled':'').'>'.esc_html($label.($st==='before'?'（販売開始前）':($st==='full'?'（満席）':($st==='ended'?'（販売終了）':'')))).'</option>';}echo'</select></label></p>';if($link){echo'<input type="hidden" name="authcore_user_id" value="'.(int)$link['authcore_user_id'].'"><p>誰扱い：'.esc_html($fixed).'</p>';}else{echo'<p><label>誰扱い<br><select required name="authcore_user_id"><option value="">選択してください</option>';foreach($attrs as$a)echo'<option value="'.(int)$a['id'].'">'.esc_html($a['name']).'</option>';echo'</select></label></p>';}$this->field('枚数','quantity','number','min="1"');$this->field('お名前','customer_name','text');$this->field('フリガナ','customer_name_kana','text');$this->field('メールアドレス','customer_email','email');echo'<p><label><input required type="checkbox" name="agreement" value="1"> 予約内容および入力したメールアドレスが正しいことを確認しました。</label></p><button name="stageart_ticket_submit" value="1">予約内容を確認</button></form></article></main>';get_footer();exit;}
 private function prepare(\WP_Post$pr,array$ps,array$attrs,?array$link):void{$fail=static fn($m)=>wp_die(esc_html($m),'チケット予約エラー',['response'=>400]);if(!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['stageart_ticket_nonce']??'')),'stageart_ticket_reserve'))$fail('不正な送信です。');$id=(int)($_POST['performance_id']??0);$x=null;foreach($ps as$v)if((int)$v['id']===$id)$x=$v;if(!$x)$fail('公演回を選択してください。');if($this->state($x,$this->start($pr->ID))!=='open')$fail('この公演回は現在予約できません。');$uid=$link?(int)$link['authcore_user_id']:(int)($_POST['authcore_user_id']??0);if(!isset($attrs[$uid]))$fail('誰扱いを選択してください。');$q=(int)($_POST['quantity']??0);if($q<1||$q>(int)$x['capacity']-$this->t->reservedQuantity($id))$fail('ご希望の枚数を確保できません。');$name=trim(sanitize_text_field(wp_unslash($_POST['customer_name']??'')));$kana=trim(sanitize_text_field(wp_unslash($_POST['customer_name_kana']??'')));$email=sanitize_email(wp_unslash($_POST['customer_email']??''));if($name===''||mb_strlen($name)>191)$fail('お名前を正しく入力してください。');if(!preg_match('/^[ァ-ヶー　]+$/u',$kana)||mb_strlen($kana)>191)$fail('フリガナは全角カタカナで入力してください。');if(!is_email($email)||empty($_POST['agreement']))$fail('メールアドレスと確認事項を確認してください。');$data=['production_id'=>$pr->ID,'performance_id'=>$id,'customer_name'=>$name,'customer_name_kana'=>$kana,'customer_email'=>$email,'quantity'=>$q,'authcore_user_id'=>$uid,'source'=>'online','reservation_no'=>$this->t->nextReservationNo('ST')];$k='stageart_ticket_confirm_'.wp_generate_uuid4();set_transient($k,['data'=>$data,'performance'=>$x],15*MINUTE_IN_SECONDS);wp_safe_redirect(add_query_arg('stageart_ticket_confirm',$k,home_url('/production/'.rawurlencode($pr->post_name).'/ticket/')));exit;}
 private function confirm(\WP_Post$pr,array$d,string$k):void{$x=$d['performance'];$a=$d['data'];if(isset($_POST['stageart_ticket_confirm_submit'])){if(!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['stageart_ticket_confirm_nonce']??'')),'stageart_ticket_confirm'))wp_die('不正な送信です。');$id=$this->t->reserveIfAvailable($a,(int)$x['capacity']);if(!$id)wp_die('販売状況が変わったため予約できません。');delete_transient($k);get_header();echo'<main class="stageart-ticket"><article><h1>予約完了</h1><p>チケット予約を受け付けました。</p><p>予約番号：<strong>'.esc_html($a['reservation_no']).'</strong></p></article></main>';get_footer();exit;}get_header();echo'<main class="stageart-ticket"><article><h1>予約内容の確認</h1>';$this->prices($pr->ID);$attrs=$this->attrs($pr->ID);echo'<dl><dt>公演名</dt><dd>'.esc_html($pr->post_title).'</dd><dt>公演回</dt><dd>'.esc_html($x['performance_date'].' '.substr((string)$x['start_time'],0,5)).'</dd><dt>予約枚数</dt><dd>'.(int)$a['quantity'].'枚</dd><dt>誰扱い</dt><dd>'.esc_html($attrs[(int)$a['authcore_user_id']]['name']??'').'</dd><dt>お名前</dt><dd>'.esc_html($a['customer_name']).'</dd><dt>フリガナ</dt><dd>'.esc_html($a['customer_name_kana']).'</dd><dt>メールアドレス</dt><dd>'.esc_html($a['customer_email']).'</dd></dl><form method="post">';wp_nonce_field('stageart_ticket_confirm','stageart_ticket_confirm_nonce');echo'<a href="'.esc_url(home_url('/production/'.rawurlencode($pr->post_name).'/ticket/')).'">入力画面に戻る</a>　<button name="stageart_ticket_confirm_submit" value="1">この内容で予約する</button></form></article></main>';get_footer();exit;}
}
