<?php
declare(strict_types=1);
namespace StageArtTicket\Presentation\Admin;
use StageArtCore\Domain\Production\ProductionRepository;
use StageArtTicket\Domain\Ticket\TicketRepository;
final class TicketAdmin{
 private TicketRepository $t;private ProductionRepository $p;
 public function __construct(){$this->t=new TicketRepository();$this->p=new ProductionRepository();}
 public function register():void{add_submenu_page('stageart-plugin','チケット管理','チケット管理','manage_options','stageart-tickets',[$this,'render']);add_action('admin_post_stageart_ticket_capacity',[$this,'capacity']);add_action('admin_post_stageart_ticket_checkin',[$this,'checkin']);add_action('admin_post_stageart_ticket_sales',[$this,'sales']);add_action('admin_post_stageart_ticket_door',[$this,'door']);}
 public function render():void{$pid=(int)($_GET['production_id']??0);$performance=(int)($_GET['performance_id']??0);$posts=get_posts(['post_type'=>'stageart_production','post_status'=>['publish','draft'],'numberposts'=>-1,'orderby'=>'date','order'=>'DESC']);echo'<div class="wrap"><h1>チケット管理</h1><form method="get"><input type="hidden" name="page" value="stageart-tickets"><select name="production_id"><option value="">公演を選択</option>';foreach($posts as$p)echo'<option value="'.(int)$p->ID.'" '.selected($pid,$p->ID,false).'>'.esc_html($p->post_title).'</option>';echo'</select> <button class="button">表示</button></form>';if(!$pid){echo'</div>';return;}$m=get_post_meta($pid);$start=(string)($m['ticket_sales_start_at'][0]??'');echo'<hr><h2>販売設定</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="stageart_ticket_sales"><input type="hidden" name="production_id" value="'.(int)$pid.'">'.wp_nonce_field('stageart_ticket_sales','_wpnonce',true,false).'<label>販売開始日時 <input type="datetime-local" name="ticket_sales_start_at" value="'.esc_attr($this->jst($start)).'"></label> <button class="button button-primary">保存</button><p class="description">販売終了は各公演日の0時です。予約画面には残席数を表示しません。</p></form><h2>公演回</h2><table class="widefat striped"><thead><tr><th>公演回</th><th>定員</th><th>予約</th><th>残席</th><th>来場</th><th>操作</th></tr></thead><tbody>';foreach($this->p->performances($pid)as$x){$r=$this->t->reservedQuantity((int)$x['id']);$c=$this->t->checkInCount((int)$x['id']);echo'<tr><td>'.esc_html($x['performance_date'].' '.substr((string)$x['start_time'],0,5)).'</td><td><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="stageart_ticket_capacity"><input type="hidden" name="production_id" value="'.(int)$pid.'"><input type="hidden" name="performance_id" value="'.(int)$x['id'].'">'.wp_nonce_field('stageart_ticket_capacity','_wpnonce',true,false).'<input type="number" name="capacity" min="0" value="'.(int)$x['capacity'].'" style="width:90px"> <button class="button">保存</button></form></td><td>'.(int)$r.'人</td><td>'.max(0,(int)$x['capacity']-$r).'人</td><td>'.(int)$c.'人</td><td><a class="button" href="'.esc_url(admin_url('admin.php?page=stageart-tickets&production_id='.$pid.'&performance_id='.$x['id'])).'">受付</a></td></tr>';}echo'</tbody></table>';if($performance)$this->list($pid,$performance);echo'</div>';}
 private function jst(string$v):string{if(!$v)return'';try{$d=new \DateTimeImmutable($v,new \DateTimeZone('UTC'));return$d->setTimezone(new \DateTimeZone('Asia/Tokyo'))->format('Y-m-d\\TH:i');}catch(\Throwable){return'';}}
 private function list(int$pid,int$performance):void{$rows=$this->t->reservations($performance);$attrs=$this->attrs($pid);echo'<h2>受付一覧</h2><p>チェックボックスを入れると予約全員を来場済みにします。部分受付には対応しません。</p><p><button type="button" class="button button-primary" onclick="document.getElementById(\'stageart-door\').style.display=\'block\'">＋ 当日券を追加</button></p><div id="stageart-door" style="display:none"><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">'.wp_nonce_field('stageart_ticket_door','_wpnonce',true,false).'<input type="hidden" name="action" value="stageart_ticket_door"><input type="hidden" name="production_id" value="'.(int)$pid.'"><input type="hidden" name="performance_id" value="'.$performance.'"><label>誰扱い <select name="authcore_user_id" required>';foreach($attrs as$a)echo'<option value="'.(int)$a['id'].'">'.esc_html($a['name']).'</option>';echo'</select></label> <label>枚数 <input type="number" name="quantity" min="1" required></label> <button class="button button-primary">OK</button></form></div><table class="widefat striped"><thead><tr><th>来場</th><th>予約番号</th><th>お名前</th><th>フリガナ</th><th>枚数</th><th>誰扱い</th><th>受付日時</th></tr></thead><tbody>';foreach($rows as$x){$checked=!empty($x['checkin_id']);echo'<tr><td>'.($checked?'☑':'<form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="stageart_ticket_checkin"><input type="hidden" name="production_id" value="'.(int)$pid.'"><input type="hidden" name="performance_id" value="'.$performance.'"><input type="hidden" name="reservation_id" value="'.(int)$x['id'].'">'.wp_nonce_field('stageart_ticket_checkin','_wpnonce',true,false).'<input type="checkbox" onchange="this.form.submit()"></form>').'</td><td>'.esc_html($x['reservation_no']).'</td><td>'.esc_html($x['customer_name']).'</td><td>'.esc_html($x['customer_name_kana']).'</td><td>'.(int)$x['quantity'].'枚</td><td>'.esc_html($attrs[(int)$x['authcore_user_id']]['name']??'—').'</td><td>'.esc_html((string)($x['checked_in_at']??'')).'</td></tr>';}if(!$rows)echo'<tr><td colspan="7">予約はありません。</td></tr>';echo'</tbody></table>';}
 private function attrs(int$pid):array{$a=[];foreach($this->p->participants($pid)as$x)if(!empty($x['auth_user_id'])){$uid=(int)$x['auth_user_id'];$a[$uid]=['id'=>$uid,'name'=>(string)$x['name']];}return$a;}
 public function sales():void{if(!current_user_can('manage_options'))wp_die('権限がありません。');check_admin_referer('stageart_ticket_sales');$pid=(int)$_POST['production_id'];$v=trim((string)($_POST['ticket_sales_start_at']??''));if($v==='')delete_post_meta($pid,'ticket_sales_start_at');else{$d=\DateTimeImmutable::createFromFormat('Y-m-d\\TH:i',$v,new \DateTimeZone('Asia/Tokyo'));if(!$d)wp_die('販売開始日時が正しくありません。');update_post_meta($pid,'ticket_sales_start_at',$d->setTimezone(new \DateTimeZone('UTC'))->format('Y-m-d H:i:s'));}wp_safe_redirect(wp_get_referer()?:admin_url('admin.php?page=stageart-tickets'));exit;}
 public function capacity():void{if(!current_user_can('manage_options'))wp_die('権限がありません。');check_admin_referer('stageart_ticket_capacity');$this->t->setCapacity((int)$_POST['performance_id'],max(0,(int)$_POST['capacity']));wp_safe_redirect(wp_get_referer()?:admin_url('admin.php?page=stageart-tickets'));exit;}
 public function checkin():void{if(!current_user_can('manage_options'))wp_die('権限がありません。');check_admin_referer('stageart_ticket_checkin');$this->t->checkIn((int)$_POST['reservation_id'],get_current_user_id());wp_safe_redirect(wp_get_referer()?:admin_url('admin.php?page=stageart-tickets'));exit;}
 public function door():void{if(!current_user_can('manage_options'))wp_die('権限がありません。');check_admin_referer('stageart_ticket_door');$pid=(int)$_POST['production_id'];$perf=(int)$_POST['performance_id'];$uid=(int)$_POST['authcore_user_id'];$qty=max(1,(int)$_POST['quantity']);if($qty>$this->t->capacity($perf)-$this->t->reservedQuantity($perf))wp_die('定員を超えるため登録できません。');$valid=false;foreach($this->attrs($pid)as$a)if($a['id']===$uid)$valid=true;if(!$valid)wp_die('誰扱いが不正です。');$this->t->doorReservation($pid,$perf,$uid,$qty);wp_safe_redirect(wp_get_referer()?:admin_url('admin.php?page=stageart-tickets'));exit;}
}
